# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-FileCopyrightText: Copyright (C) 2026 OCUDU contributors
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

# Example configuration file for F1-C configuration with DTLS enabled.
#
# Each F1-C gateway with DTLS enabled will require:
# - ca_cert_filename: filename of the certificate provided by the CA
# - cert_filename: our own certificate
# - key_filename: our own key

f1ap:
  addrs: 127.0.10.1
  bind_addrs: 127.0.10.2
  dtls:
    cert_filename: "/tmp/client-cert.pem"
    key_filename: "/tmp/client-key.pem"
    ca_cert_filename: "/tmp/ca-cert.pem"
