// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI

#pragma once

#include "ocudu/adt/circular_array.h"
#include "ocudu/adt/span.h"
#include "ocudu/adt/static_vector.h"
#include "ocudu/ofh/compression/compression_params.h"
#include "ocudu/ofh/ofh_constants.h"
#include "ocudu/ofh/transmitter/ofh_transmitter_configuration.h"
#include "ocudu/ran/slot_point.h"
#include <array>
#include <atomic>
#include <limits>
#include <optional>
#include <random>
#include <string_view>
#include <vector>

namespace ocudu {
namespace ofh {
namespace test {

/// List of beam-ports of a downlink resource grid to be transmitted by the RU, in eAxC order.
using dl_beam_list = static_vector<unsigned, MAX_NOF_SUPPORTED_EAXC>;

/// \brief Lock-free registry of the beam-ports transmitted in every downlink slot.
///
/// The DU emulator writes the entry of a slot before handing its resource grid to the RU, and the test Ethernet gateway
/// reads it when the C-Plane messages of the slot are transmitted.
class dl_beam_registry
{
  /// Number of slots stored in the ring. It is implementation defined, the selected size should be sufficient to not
  /// overwrite the entry of a slot whose messages are still processed by RU/test gateway.
  static constexpr unsigned ring_size = 64;
  /// Number of frame identifiers encoded in the C-Plane messages.
  static constexpr unsigned ofh_max_nof_sfn = 256;
  /// Key of an entry that is being written or was never written.
  static constexpr unsigned invalid_key = std::numeric_limits<unsigned>::max();

  /// Ring entry.
  struct entry {
    std::atomic<unsigned>                                     key{invalid_key};
    std::atomic<unsigned>                                     nof_beams{0};
    std::array<std::atomic<unsigned>, MAX_NOF_SUPPORTED_EAXC> beams = {};
  };

public:
  /// Registers the beam-ports transmitted in the given slot.
  void write(slot_point slot, const dl_beam_list& beams)
  {
    unsigned idx = get_slot_entry(slot);
    entry&   e   = ring[idx];

    // Make sure the reader observing new data also observes the invalid key, until all beams are written.
    e.key.store(invalid_key, std::memory_order_relaxed);
    e.nof_beams.store(beams.size(), std::memory_order_release);
    for (unsigned i = 0, i_end = beams.size(); i != i_end; ++i) {
      e.beams[i].store(beams[i], std::memory_order_release);
    }
    e.key.store(idx, std::memory_order_release);
  }

  /// Returns the beam-ports registered for the given slot, or \c std::nullopt if there is none.
  std::optional<dl_beam_list> read(slot_point slot) const
  {
    unsigned     idx = get_slot_entry(slot);
    const entry& e   = ring[idx];

    if (e.key.load(std::memory_order_acquire) != idx) {
      return std::nullopt;
    }

    dl_beam_list beams(std::min<unsigned>(e.nof_beams.load(std::memory_order_acquire), MAX_NOF_SUPPORTED_EAXC));
    for (unsigned i = 0, i_end = beams.size(); i != i_end; ++i) {
      beams[i] = e.beams[i].load(std::memory_order_acquire);
    }

    // Discard the entry if it was overwritten while reading it.
    if (e.key.load(std::memory_order_relaxed) != idx) {
      return std::nullopt;
    }
    return beams;
  }

private:
  /// Gets the index of a C-Plane message slot in the internal ring buffer, where the frame identifier is 8 bits wide.
  static unsigned get_slot_entry(slot_point slot)
  {
    return slot_point(
               slot.numerology(), slot.sfn() % ofh_max_nof_sfn, slot.subframe_index(), slot.subframe_slot_index())
        .count();
  }

  circular_array<entry, ring_size> ring;
};

/// Decoded section extension 1.
struct decoded_cplane_section_ext_1 {
  /// Beamforming weights compression parameters, decoded from the bfwCompHdr field.
  ru_compression_params compr_params;
  /// Packed beamforming weights, including the bfwCompParam field when present.
  span<const uint8_t> packed_weights;
};

/// Decoded Control-Plane section type 1 message carrying a single section.
struct decoded_cplane_section_type_1 {
  /// Section type.
  unsigned section_type;
  /// Number of sections in the message.
  unsigned nof_sections;
  /// Start symbol, given in the radio application header.
  unsigned start_symbol;
  /// Start PRB of the section.
  unsigned start_prb;
  /// Number of PRBs of the section, zero means all the PRBs.
  unsigned nof_prb;
  /// Number of symbols of the section.
  unsigned nof_symbols;
  /// Section extension flag.
  bool ef;
  /// Beam identifier.
  unsigned beam_id;
  /// Optional section extension 1.
  std::optional<decoded_cplane_section_ext_1> extension_1;
};

/// \brief Decodes a Control-Plane message carrying a single section type 1, as generated by the OFH transmitter.
///
/// The message is expected to be an Ethernet frame with a VLAN tag followed by an eCPRI real-time control message.
///
/// \param[in] message Ethernet frame to parse.
/// \param[in] nof_trx Number of O-RU TRXs, i.e., number of beamforming weights of a section extension 1.
/// \return The parsed fields, or \c std::nullopt if the message is malformed.
std::optional<decoded_cplane_section_type_1> decode_cplane_section_type_1(span<const uint8_t> message,
                                                                          unsigned            nof_trx);

/// \brief Generates the beam-ports list of a Category B downlink resource grid.
///
/// The first grids cover the corner cases: the first and last beams, the region A (port-selection) beams only, the
/// region B beams only, an empty grid and a mix of both regions. The rest carry random beam-port sets of increasing
/// size.
///
/// \param[in,out] rgen      Random generator used for the random beam-port sets.
/// \param[in] grid_index    Index of the resource grid in the pool.
/// \param[in] nof_beams     Total number of beams of the antenna topology, i.e., number of resource grid ports.
/// \param[in] nof_trx       Number of antenna ports of the topology, i.e., number of port-selection beams.
/// \param[in] max_num_beams Maximum number of beam-ports transmitted per slot, given by the number of DL eAxCs.
dl_beam_list generate_beam_pattern(std::mt19937& rgen,
                                   unsigned      grid_index,
                                   unsigned      nof_beams,
                                   unsigned      nof_trx,
                                   unsigned      max_num_beams);

/// Downlink C-Plane message checker configuration.
struct dl_cplane_checker_config {
  /// Number of PRBs of the cell.
  unsigned nof_prb;
  /// Downlink eAxCs, the k-th one carries the k-th transmitted beam-port.
  std::vector<unsigned> dl_eaxc;
  /// Downlink beamforming configuration. Unset value means Category A.
  std::optional<transmitter_beamforming_config> beamforming;
};

/// \brief Checker of the downlink C-Plane messages transmitted by the DU.
///
/// It checks that every message is a valid C-Plane message with the expected eAxC, containing a valid section type-1.
/// For Category B, the beam identifier and the section extension 1 carrying the beam weights are checked against an
/// independent compression of the beam weights codebook.
class dl_cplane_checker
{
  /// Offset between the beam identifier of a beam-port and the one encoded in the C-Plane messages.
  static constexpr unsigned beam_id_offset = 1;
  /// Maximum number of errors printed.
  static constexpr unsigned max_nof_printed_errors = 10;

public:
  dl_cplane_checker(const dl_beam_registry& beam_registry_, const dl_cplane_checker_config& config_);

  /// Checks the given downlink C-Plane message, transmitted in the given slot and eAxC.
  void check(span<const uint8_t> message, slot_point slot, unsigned eaxc);

  /// Returns the number of errors detected.
  unsigned get_nof_errors() const { return nof_errors.load(std::memory_order_relaxed); }

private:
  /// Accounts an error and prints it, up to a maximum number of printed errors.
  void report_error(slot_point slot, unsigned eaxc, std::string_view error);

  const dl_beam_registry&        beam_registry;
  const dl_cplane_checker_config config;
  /// Number of O-RU TRXs, i.e., number of weights per beam.
  unsigned nof_trx = 0;
  /// Expected packed beamforming weights per beam-port.
  std::vector<std::vector<uint8_t>> expected_weights;
  std::atomic<unsigned>             nof_errors{0};
};

} // namespace test
} // namespace ofh
} // namespace ocudu
